package:
  name: pycellanalyst
  version: 1.1.0

source:
  git_url: https://github.com/siboles/pyCellAnalyst.git
  git_rev: 1.1.0

requirements:
  build:
    - python
    - tetmesh
    - cgal
    - tbb
    - vtk > 6.0.0
    - simpleitk
    - numpy
    - scipy
    - matplotlib
    - scikit-learn
    - xlrd
    - xlwt
    - wquantiles
    - febio
  run:
    - python
    - tetmesh
    - cgal
    - tbb
    - vtk > 6.0.0
    - simpleitk
    - numpy
    - scipy
    - matplotlib
    - scikit-learn
    - xlrd
    - xlwt
    - wquantiles
    - febio

test:
  imports:
    - pyCellAnalyst.Volume
    - pyCellAnalyst.CellMech

about:
  home: https://github.com/siboles/pyCellAnalyst
  summary:  
