package:
  name: pycellanalyst
  version: 1.2

source:
  git_url: https://github.com/siboles/pyCellAnalyst.git
  git_rev: 1.2

requirements:
  build:
    - python
    - future
    - tetmesh
    - cgal
    - tbb
    - vtk
    - simpleitk 1.0*
    - numpy
    - scipy
    - matplotlib
    - scikit-learn
    - xlrd
    - xlwt
    - wquantiles
    - febio 0.2*
  run:
    - python
    - future
    - tetmesh
    - cgal
    - tbb
    - vtk
    - simpleitk 1.0*
    - numpy
    - scipy
    - matplotlib
    - scikit-learn
    - xlrd
    - xlwt
    - wquantiles
    - febio 0.2*

test:
  imports:
    - pyCellAnalyst.Volume
    - pyCellAnalyst.CellMech

about:
  home: https://github.com/siboles/pyCellAnalyst
  summary: 'An extensive module for image processing, segmentation, and deformation analysis. Initially aimed at processing 3-D microscopy of cells, this may have applications for other data types as well.'
  license: MIT License
